CIS341_Project/Models/Assignment.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CIS341_Project.Models
{
    public class Assignment
    {
        public int AssignmentID { get; set; } //PK
        public int TaskID { get; set; } //FK
        public int HouseholdMemberID { get; set; } //FK
        [DisplayName("Date Due")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [DisplayName("Assignment Completed?")]
        public bool Completed { get; set; }

        //Navigation properties
        [DisplayName("Task")]
        public Task Task { get; set; } = null!;
        [DisplayName("HouseholdMember")]
        public HouseholdMember HouseholdMember { get; set; } = null!;
    }
}

CIS341_Project/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CIS341_Project.Data;
using CIS341_Project.Models;
using CIS341_Project.Models.DTO;
using Microsoft.AspNetCore.Authorization;

namespace CIS341_Project.Controllers
{
    ///<summary>
    ///This is a controller which is used to perform CRUD on the Assignments in the application and also
    ///let users view their assigned tasks, or admins view all assigned tasks.
    /// </summary>
    public class AssignmentsController : Controller
    {
        /// <value>
        /// _context is the private field with a reference to the FamilySchedulerContext.
        /// </value>
        private readonly FamilySchedulerContext _context;
        ///<summary>
        ///This is the constructor for the AssignmentsController that injects the FamilySchedulerContext via dependency injection.
        /// </summary>
        /// <param name="context">Parameter for the DbContext to be injected.</param>
        /// <returns>Nothing</returns>
        public AssignmentsController(FamilySchedulerContext context)
        {
            _context = context;
        }

        ///<summary>
        ///This is the action method for the path GET: Assignments/Create it adds HouseholdMembers and Tasks to a select list in viewbag
        ///to be displayed in the view.
        /// </summary>
        /// <returns>Returns the associated ViewResult to render Assignments/Create view.</returns>

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["HouseholdMemberName"] = new SelectList(_context.HouseholdMembers, "HouseholdMemberID", "Name");
            ViewData["TaskDescription"] = new SelectList(_context.Tasks, "TaskID", "Description");
            return View();
        }

        ///<summary>
        ///This is the action method for the path POST: Assignments/Create it validates input data and then creates an assignment if sucessfull or if it
        ///fails validation it will add HouseholdMembers and Tasks to a select list in viewbag along with the currently selected 
        ///values to be displayed in the view.
        /// </summary>
        /// <param name="assignmentDTO">Takes a AssignmentDTO object that is bound to by the values from the POST request.</param>
        /// <returns>If sucessful returns a redirect to the /Assignments/AllAssignments. If failed validation it returns the failed bound AssignmentDTO
        /// to the Create view.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("AssignmentID,TaskID,HouseholdMemberID,Date,Completed")] AssignmentDTO assignmentDTO)
        {
            if (ModelState.IsValid)
            {
                Assignment assignment = new Assignment
                {
                    Completed = assignmentDTO.Completed,
                    Date = assignmentDTO.Date,
                    HouseholdMemberID = assignmentDTO.HouseholdMemberID,
                    TaskID = assignmentDTO.TaskID
                };
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(AllAssignments));
            }
            ViewData["HouseholdMemberID"] = new SelectList(_context.HouseholdMembers, "HouseholdMemberID", "Name", assignmentDTO.HouseholdMemberID);
            ViewData["TaskID"] = new SelectList(_context.Tasks, "TaskID", "Description", assignmentDTO.TaskID);
            return View(assignmentDTO);
        }

        [Authorize(Roles = "Admin")]
        ///<summary>
        ///This is the action method for the path GET: Assignments/Edit/{id} it adds HouseholdMembers and Tasks to a select list in 
        ///viewbag along with the currently selected values for the requested Assignment to be displayed in the view.
        /// </summary>
        /// <param name="id">the id of a requested assignment (AssignmentID)</param>
        /// <returns>Returns NotFound if not a good id. If it is a good ID it returns the associated view with the assignmentDTO for said Assignment with that ID</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.Include(i => i.Task)
                .Include(i => i.HouseholdMember)
                .Where(i => i.AssignmentID == id)
                .FirstOrDefaultAsync();
            if (assignment == null)
            {
                return NotFound();
            }
            AssignmentDTO assignmentDTO = new AssignmentDTO(assignment);
            ViewData["HouseholdMemberID"] = new SelectList(_context.HouseholdMembers, "HouseholdMemberID", "Name", assignmentDTO.HouseholdMemberID);
            ViewData["TaskID"] = new SelectList(_context.Tasks, "TaskID", "Description", assignmentDTO.TaskID);
            return View(assignmentDTO);
        }

        ///<summary>
        ///This is the action method for the path POST: Assignments/Edit/{id} it edits the selected Assignments with the values from the post.
        /// </summary>
        /// <param name="id">the id of a requested assignment (AssignmentID)</param>
        /// <param name="assignmentDTO">Takes a AssignmentDTO object that is bound to by the values from the POST request.</param>
        /// <returns>Returns NotFound if not a good id. If the values for POST request are not valid it returns the TaskDTO and adds
        /// HouseholdMembers and Tasks to select list in the view bag. If it is a good ID it returns a redirect for the AllAssignments view.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("AssignmentID,TaskID,HouseholdMemberID,Date,Completed")] AssignmentDTO assignmentDTO)
        {
            if (id != assignmentDTO.AssignmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Assignment assignment = new Assignment
                    {
                        AssignmentID = assignmentDTO.AssignmentID,
                        Completed = assignmentDTO.Completed,
                        Date = assignmentDTO.Date,
                        HouseholdMemberID = assignmentDTO.HouseholdMemberID,
                        TaskID = assignmentDTO.TaskID
                    };
                    _context.Update(assignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentExists(assignmentDTO.AssignmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AllAssignments));
            }
            ViewData["HouseholdMemberID"] = new SelectList(_context.HouseholdMembers, "HouseholdMemberID", "Name", assignmentDTO.HouseholdMemberID);
            ViewData["TaskID"] = new SelectList(_context.Tasks, "TaskID", "Description", assignmentDTO.TaskID);
            return View(assignmentDTO);
        }

        ///<summary>
        ///This is the action method for the path GET: Assignments/Delete/{id} checks if the id is valid and if so it confirms with the user if they do want
        ///to delete the selected Assignment.
        /// </summary>
        /// <param name="id">The id of a requested assignment to be deleted(AssignmentID).</param>
        /// <returns>Returns NotFound if not a good id. If it is a good ID it returns the associated view with the assignmentDTO for said Assignment with that ID.</returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .Include(a => a.HouseholdMember)
                .Include(a => a.Task)
                .FirstOrDefaultAsync(m => m.AssignmentID == id);
            if (assignment == null)
            {
                return NotFound();
            }
            AssignmentDTO assignmentDTO = new AssignmentDTO(assignment);
            return View(assignmentDTO);
        }

        ///<summary>
        ///This is the action method for the path POST: Assignments/Delete/{id}, this will delete the requested Assignment from the DB
        /// </summary>
        /// <param name="id">the id of a requested assignment to be deleted(AssignmentID).</param>
        /// <returns>Returns a problem if there is a issue with the DB, otherwise it will redirect to the AllAssignments view after deletion.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Assignments == null)
            {
                return Problem("Entity set 'FamilySchedulerContext.Assignments'  is null.");
            }
            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment != null)
            {
                _context.Assignments.Remove(assignment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(AllAssignments));
        }

        private bool AssignmentExists(int id)
        {

CIS341_Project/Views/Assignments/AllAssignments.cshtml
@using CIS341_Project.Data
@model List<CIS341_Project.Models.DTO.AllAssignmentsDTO>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (ViewBag.NoAssignments != null)
{
    <h2>There are no assignments <a class = "link" asp-area="" asp-page="/GenerateSchedule">Generate Schedule</a></h2>
}
<table class="table table-striped table-hover table-bordered border-secondary overflow-auto">
    @*Make the first row with the names and the first column saying date*@
    <tr>
        <th><a asp-controller="Assignments" asp-action="Create">New Assignment</a></th>
        @foreach (var name in ViewBag.HouseholdMembersWithAssignments)
        {
            <th>
                @name
            </th>
        }
    </tr>
    @foreach (CIS341_Project.Models.DTO.AllAssignmentsDTO aADTO in Model)
    {
        <tr>
            <th>
                @aADTO.DueDate.ToShortDateString()
            </th>
            @foreach (List<CIS341_Project.Models.DTO.AssignmentDTO> householdMembersAssignments in aADTO.HouseholdMembersAssignments)
            {
                <td>
                    @foreach (CIS341_Project.Models.DTO.AssignmentDTO assignment in householdMembersAssignments)
                    {
                        <div>
                            <input asp-for=@assignment.Completed disabled /> @assignment.TaskDescription <a asp-action="Edit" asp-route-id="@assignment.AssignmentID">Edit</a> | <a asp-action="Delete" asp-route-id="@assignment.AssignmentID">Delete</a>
                        </div>
                    }
        </td>
                }
        </tr>
    }
    @*Make the rest of the rows with the passed in model everytime the date changes new row*@
</table>

CIS341_Project/Views/Assignments/Create.cshtml
@model CIS341_Project.Models.DTO.AssignmentDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaskID" class="control-label"></label>
                <select asp-for="TaskID" class ="form-control" asp-items="ViewBag.TaskDescription"></select>
            </div>
            <div class="form-group">
                <label asp-for="HouseholdMemberID" class="control-label"></label>
                <select asp-for="HouseholdMemberID" class ="form-control" asp-items="ViewBag.HouseholdMemberName"></select>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllAssignments">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CIS341_Project/Views/Assignments/Delete.cshtml
@model CIS341_Project.Models.DTO.AssignmentDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HouseholdMemberName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HouseholdMemberName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AssignmentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="AllAssignments">Back to List</a>
    </form>
</div>

CIS341_Project/Views/Assignments/Edit.cshtml
@model CIS341_Project.Models.DTO.AssignmentDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Assignment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AssignmentID" />
            <div class="form-group">
                <label asp-for="TaskID" class="control-label"></label>
                <select asp-for="TaskID" class="form-control" asp-items="ViewBag.TaskID"></select>
                <span asp-validation-for="TaskID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HouseholdMemberID" class="control-label"></label>
                <select asp-for="HouseholdMemberID" class="form-control" asp-items="ViewBag.HouseholdMemberID"></select>
                <span asp-validation-for="HouseholdMemberID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AllAssignments">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CIS341_Project/Views/Assignments/MyAssignedTasks.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<CIS341_Project.Models.DTO.AllAssignmentsDTO>
@{
}
<h1>Tasks for @ViewBag.loggedInHouseHoldmember</h1>

@if (ViewBag.NoAssignmentsForMember != null)
{
    <h2>You have no tasks ask your parent to give you some</h2>
}
<table class="table table-striped table-hover table-bordered border-secondary overflow-auto">
    @*Make the first row with the names and the first column saying date*@
    <tr>
        <th>Date</th>
        @foreach (var name in ViewBag.HouseholdMembersWithAssignments)
        {
            <th>
                @name
            </th>
        }
    </tr>
    @foreach (CIS341_Project.Models.DTO.AllAssignmentsDTO aADTO in Model)
    {
        <tr>
            <th>
                @aADTO.DueDate.ToShortDateString()
            </th>
            @foreach (List<CIS341_Project.Models.DTO.AssignmentDTO> householdMembersAssignments in aADTO.HouseholdMembersAssignments)
            {
                <td>
                    @foreach (CIS341_Project.Models.DTO.AssignmentDTO assignment in householdMembersAssignments)
                    {
                        <div>
                            <input asp-for=@assignment.Completed disabled /> @assignment.TaskDescription
                                @if (@assignment.Completed) {
                                    <a asp-action="UpdateAssignmentCompletion" asp-route-id="@assignment.AssignmentID">Mark as incomplete</a>
                                }
                                else{
                                <a asp-action="UpdateAssignmentCompletion" asp-route-id="@assignment.AssignmentID">Mark as complete</a>
                                }
                        </div>
                    }
                </td>
            }
        </tr>
    }
    @*Make the rest of the rows with the passed in model everytime the date changes new row*@
</table>